### ISSUE TITLE
Ready check and file import

### ISSUE THREAD

**Issue by Xstoudi** [mylims/mylims#97]
## Todo:
- [x] Use an enum to describe the status of a revision
- [x] Fix error on panel admin (hostUrl undefined)
- [x] Rename "files" collection with a prefix
- [x] "Check" command that works on "files" collection with same options as "Sync" command
- [x] Create a new collection that store imported files
- [x] It may be possible to config the storage location on admin panel

## Imported files naming strategy
When imported, files must be organized like this:
- Filename: random UUID
- Extension: original file extension
- Location: `subfolderA/subfolderB/filename.extension`
With `subfolderA` defined as the two first characters of the UUID and `subfolderB` defined as the two next characters of the UUID.

## Check command workflow
```
for each file related to the given file_sync_option with last revision set to "pending" state
    if ready checks are okay
        set state to "importing"
        copy the file on our system
        generate a new subfolder to store the imported file
        set state to "imported"
    else
        test next file
```
